#pragma once
#include <string>
#include <ctime>
enum class UserRole { USER, ADMIN };
class UserAccount {
public:
    std::string username;
    std::string hashedPassword;
    std::string fullName;
    std::string email;
    std::string phone;
    UserRole role;
    bool isAutoGeneratedPassword;
    time_t createdAt;
    time_t lastLogin;
    std::string walletId;
    UserAccount();
    UserAccount(const std::string& username, const std::string& hashedPassword, const std::string& fullName, const std::string& email, const std::string& phone, UserRole role, bool isAutoGeneratedPassword, time_t createdAt, time_t lastLogin, const std::string& walletId);
    std::string serialize() const;
    static UserAccount deserialize(const std::string& data);
}; 