name: dev

on:
  push:
   branches: [dev]

jobs:
   build:
    name: uy
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    - name: hello
      id: hello2 
      run: echo "dev"
      

