name: CI

on:
  push:

jobs:
   build:
    name: uy
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    - name: hello
      id: hello2 
      run: echo "uy"
      
   build2:

    runs-on: ubuntu-latest

    needs: build

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    - name: hello
      id: hello1
      run: echo "fdsvcb"
    - if: ${{ steps.hello2}}
      name: fhhj
      run: echo "hgf"
